<a href="https://colab.research.google.com/github/Dimasputra2530/SparkqueIntern/blob/main/Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORT LIBRARY

In [4]:
import pandas as pd
import numpy as npe
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

#LOAD DATASET

In [2]:
df = pd.read_csv('orders.csv')

In [9]:
df.head()

,Coffee Type,Roast Type,Size,Unit Price,Sales,Coffee Type Name,Roast Type Name,Loyalty Card
0,Rob,M,1.0 kg,$9.95,$19.90,Robusta,Medium,Yes
1,Exc,M,0.5 kg,$8.25,$41.25,Excelsa,Medium,Yes
2,Ara,L,1.0 kg,$12.95,$12.95,Arabica,Light,Yes
3,Exc,M,1.0 kg,$13.75,$27.50,Excelsa,Medium,No
4,Rob,L,2.5 kg,$27.49,$54.97,Robusta,Light,No

#Exploratory Data Analysis

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Coffee Type       1000 non-null   object
 1   Roast Type        1000 non-null   object
 2   Size              1000 non-null   object
 3   Unit Price        1000 non-null   object
 4   Sales             1000 non-null   object
 5   Coffee Type Name  1000 non-null   object
 6   Roast Type Name   1000 non-null   object
 7   Loyalty Card      1000 non-null   object
dtypes: object(8)
memory usage: 62.6+ KB

In [7]:
df.describe()

,Coffee Type,Roast Type,Size,Unit Price,Sales,Coffee Type Name,Roast Type Name,Loyalty Card
count,1000,1000,1000,1000,1000,1000,1000,1000
unique,4,3,4,40,196,4,3,2
top,Ara,M,0.5 kg,$5.97,$17.91,Arabica,Medium,No
freq,264,334,268,47,21,264,334,521

In [5]:
df.isnull().sum()

Coffee Type         0
Roast Type          0
Size                0
Unit Price          0
Sales               0
Coffee Type Name    0
Roast Type Name     0
Loyalty Card        0
dtype: int64

#Check for duplicate data

In [10]:
df.duplicated().sum()

np.int64(519)

#Remove missing values

In [11]:
df = df.dropna()

#Remove duplicate

In [12]:
df = df.drop_duplicates()

# Detect & Handle Outliers

In [13]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Remove outliers
    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("\nOutliers removed using IQR.")

Outliers removed using IQR.

# Incorrect Data Types

In [19]:
# Pastikan kolom berbentuk string dulu
df["Unit Price"] = df["Unit Price"].astype(str)
df["Sales"] = df["Sales"].astype(str)

# Bersihkan simbol $ dan koma
df["Unit Price"] = df["Unit Price"].str.replace("$", "", regex=False).str.replace(",", "")
df["Sales"] = df["Sales"].str.replace("$", "", regex=False).str.replace(",", "")

# Convert ke float
df["Unit Price"] = pd.to_numeric(df["Unit Price"], errors="coerce")
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")

print(df.dtypes)

Coffee Type          object
Roast Type           object
Size                 object
Unit Price          float64
Sales               float64
Coffee Type Name     object
Roast Type Name      object
Loyalty Card         object
dtype: object